# Make sure we have our ENV_PERSONALWEBSITE_DIR environment variable set.
if [ -z "$ENV_PERSONALWEBSITE_DIR" ]; then
    echo "Need to set ENV_PERSONALWEBSITE_DIR"
    exit 1
fi

# Make sure we have our ENV_FGWEBAPP_DIR environment variable set.
if [ -z "$ENV_FGWEBAPP_DIR" ]; then
    echo "Need to set ENV_FGWEBAPP_DIR"
    exit 1
fi

# Make sure we have our ENV_ADDRESSBOOK_DIR environment variable set.
if [ -z "$ENV_ADDRESSBOOK_DIR" ]; then
    echo "Need to set ENV_ADDRESSBOOK_DIR"
    exit 1
fi

PERSONALWEBSITE_CONFIG_DIR=$ENV_PERSONALWEBSITE_DIR/config
export PERSONALWEBSITE_CONFIG_DIR

FGWEBAPP_CONFIG_DIR=$ENV_FGWEBAPP_DIR/config
export FGWEBAPP_CONFIG_DIR

ADDRESSBOOK_CONFIG_DIR=$ENV_ADDRESSBOOK_DIR/config
export ADDRESSBOOK_CONFIG_DIR

# Log4J properties
PERSONALWEBSITE_LOG4J_PROPERTY="-Dpersonalwebsite.log4j.file=$PERSONALWEBSITE_CONFIG_DIR/log4j.xml"
FELLOWSHIPGROUP_LOG4J_PROPERTY="-Dfellowshipgroups.log4j.file=$FGWEBAPP_CONFIG_DIR/log4j.xml"
ADDRESSBOOK_LOG4J_PROPERTY="-Daddressbook.log4j.file=$ADDRESSBOOK_CONFIG_DIR/log4j.xml"

# Runtime directory properties
PERSONALWEBSITE_RUNTIME_PROPERTY="-Dpersonalwebsite.runtime.properties.dir=$PERSONALWEBSITE_CONFIG_DIR"
FELLOWSHIPGROUP_RUNTIME_PROPERTY="-Dfellowshipgroups.runtime.properties.dir=$FGWEBAPP_CONFIG_DIR"
ADDRESSBOOK_RUNTIME_PROPERTY="-Daddressbook.runtime.properties.dir=$ADDRESSBOOK_CONFIG_DIR"

export JAVA_OPTS="${PERSONALWEBSITE_LOG4J_PROPERTY} ${FELLOWSHIPGROUP_LOG4J_PROPERTY} ${ADDRESSBOOK_LOG4J_PROPERTY} ${PERSONALWEBSITE_RUNTIME_PROPERTY} ${FELLOWSHIPGROUP_RUNTIME_PROPERTY} ${ADDRESSBOOK_RUNTIME_PROPERTY}"
